### ISSUE TITLE
Status Bar is Hidden .

### ISSUE THREAD

**Issue by baquer** [amahi/ios#133]
**Current Behaviour**
Status Bar is hidden.

**Actual Behaviour**
Status Bar should be present.

**Screenshot of the issue**
![screenshot 2018-11-17 at 10 49 25 pm](https://user-images.githubusercontent.com/32494694/48663848-10b74e80-eabc-11e8-9765-6e215e85d5fa.png)

**How to fix**
Screenshot 
![screenshot 2018-11-17 at 10 51 51 pm](https://user-images.githubusercontent.com/32494694/48663867-56741700-eabc-11e8-978a-ac3f13c4fdb7.png)
**Would You Like To Work On This Issue**
Yes.

**Comment by cpg** [comment]
Well, when one is watching a movie it's not nice to see the status bar.

However, the static setting is always or never in this simple configuration. Ideally we'd have it hidden when playing or browsing files (i.e. when a handler is handling a file), not during the rest of the app, browsing files.

So, I am not sure we want this status bar, because of how bright it is in some circumstances.

**Comment by baquer** [comment]
Okay , yeah that's why I was wondering, why it is hidden , I am closing this issue and PR .
Thanks for the explanation.

**Comment by baquer** [comment]
@cpg , what we could do is , we hide the status bar in browsing files and in video player  storyboards, while in other storyboards me reflect the status bar . 
Is this a good idea??

**Comment by cpg** [comment]
If it can be made to work to dynamically hide either

1) when the video player is playing, or
2) when the controls of the video player disappear

i.e. it's ok to show the status bar when controls also show. perhaps that is easy, since I do remember we manage the controls (@codedentwickler wrote some code to handle them, iirc).

**Comment by cpg** [comment]
Just to be clear, I _think_ the logic here would be to leave the status bar (SB) visible by default all the time, then

* only set the SB to hidden when the controls are hidden
* only set the SB to shown when
  * the controls are shown
  * the video player quits (the video ends without displaying the controls)

**Comment by baquer** [comment]
@cpg ,thanks , i will work on this and make a PR soon.
