### ISSUE TITLE
Implementation of Thumbnail Preview

### ISSUE THREAD

**Issue by eddyteddy3** [amahi/ios#156]

**Comment by iswiftshek** [comment]
What is this issue for? Please share something in the description @eddyteddy3

**Comment by eddyteddy3** [comment]
I saw this on the project list under AMAHI iOS App while applying for GSoC. how can i find mentor for this ? @iswiftshek

**Comment by iswiftshek** [comment]
This feature has actually been done already #149  

Anyways, how about you join Amahi's [IRC channel](https://www.amahi.org/community)? 
You can talk about GSoC, speak to the mentors and have any discussion there.

**Comment by cpg** [comment]
I looked into caching/perf issues with music artwork images

1) the artwork images (for mp3 files) take a bit to reload when I reopen the app
2) the server sees accesses for the mp3 file (at full size, according to the log, but it could be just a fraction of the file, because the logs do not reflect that)
3) the console says, over and over, every time `["Audio Thumbnail for http://IP/files?s=Music&p=/name.mp3&mtime=1556558876&session=123 was stored"]` 

If one is to believe the console logs, it gets generated every time the app accesses the folder *after restarting*

So, does the `was stored` message mean it was re-fetched and re-stored?
