### ISSUE TITLE
support for flac files

### ISSUE THREAD

**Issue by cpg** [amahi/ios#172]
I came across a `.flac` file that I wanted to play and the app choked on it. I thought we supported it.

`FLAC audio bitstream data, 16 bit, stereo, 44.1 kHz, 166415172 samples`

(I can't see the log at the moment -- maybe we can find some public file to debug/test with)

**Comment by codedentwickler** [comment]
Looking into this issue. I have downloaded a sample .flac file online.

**Comment by codedentwickler** [comment]
I figured out the issue and found a fix.

The issue is that all audio files are currently played with the default iOS `AVPlayerViewController` to enable remote control from control center. Because the .flac format is a special type of compressed file, the default `AVPlayerViewController` does not support playing such file, that is why it choked on it.

VLCKit on the other end support playing such file. I was able to play the .flac file I downloaded with the current video player powered with VLCKit. I'll create a PR soon with the update.
