### ISSUE TITLE
photo browser improvements

### ISSUE THREAD

**Issue by cpg** [amahi/ios#63]
The `Close` button is white and to the top-right. this is often hard to see in bright images. the other controls are at the top left, and in electric blue color.

I think the photo browser `Close` should, for consistency, be also on the top left and in the same color (make it a constant somewhere  if possible, so that later we can change them consistently when we tweak the UI).

The controls and the image name as well as the line and counter may be ok as white for now, however, I think they should fade in a few seconds.

**Comment by Poppy22** [comment]
Hello! I would like to start working on this. I am interested to participate in GSoC.

**Comment by cpg** [comment]
@Poppy22 You don't need permission to work on things. Just try and implement a feature (or fix a bug) to show us your skills. So, go ahead!

**Comment by cpg** [comment]
Let's add this work to #246

**Comment by anubhavpulkit** [comment]
We can't change the position of the close button because of limited customization option in Lightbox image viewer. We can change the text color to electric blue and other customization possibilities are mention [here](https://github.com/hyperoslo/Lightbox/blob/master/Source/LightboxConfig.swift ).

### Screenshot after color change
![lightbox](https://user-images.githubusercontent.com/47811606/90343093-0af0f300-e02b-11ea-9b76-c3634b815eaf.png)
